device: cuda
face_detector:
  mediapipe_max_num_faces: 3
  mediapipe_static_image_mode: true
  mediapipe_min_det_conf: 0.8
  mediapipe_min_track_conf: 0.5
  ultralight: false
  padding: 0.0
  mediapipe_backend: tasks
  mediapipe_delegate: gpu
  mediapipe_task_model: models/face_landmarker.task
gaze_estimator:
  use_dummy_camera_params: true
  camera_params: configs/benchmark_camera_params.yaml
  normalized_camera_params: configs/normalized_camera_params.yaml
  model_path: model_path.pth
image:
  width: null
  height: null
