image_width: 640
image_height: 480
camera_matrix:
  rows: 3
  cols: 3
  data: [554, 0.0, 320, 0.0, 554, 240, 0.0, 0.0, 1.0]
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
